[phases.setup]
nixPkgs = ['...', 'python311', 'gcc', 'postgresql']

[phases.install]
cmds = [
  'pip install -r backend/requirements.txt'
]

[start]
cmd = 'cd backend && python manage.py collectstatic --noinput && python manage.py migrate && gunicorn backend.wsgi --chdir backend --bind 0.0.0.0:$PORT'
