services:
  - type: web
    name: prairies-africa-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: echo "No build required for static site"
    staticSiteGenerator: none
    publishDir: ./
    routes:
      - type: redirect
        source: /api/(.*)
        destination: https://prairies-africa-backend.onrender.com/api/$1
        status: 200
